#!/bin/bash
#
#/etc/rc.d/init.d/crtmp
# crtmpserver      This shell script takes care of starting and stopping
#
#### BEGIN INIT INFO
# Author: Brian Jones jonesy@cs.princeton.edu
#
# chkconfig: 2345 13 87
# description: crtmpserver is the C-RTMP-Server Service daemon.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

ROOTDIR=/usr/local/dtedu/crtmpserver
PATH=/usr/local/dtedu/crtmpserver/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=crtmpserver
DAEMON_ARGS="--daemon /usr/local/dtedu/crtmpserver/etc/crtmpserver.lua"
NAME=crtmpserver
DESC=crtmpserver
PIDFILE=/var/run/$NAME.pid

start() {
        echo -n "Starting crtmpserver Server: "
        if [ -f $PIDFILE ]; then
                PID=`cat $PIDFILE`
                echo crtmpserver already running: $PID
                exit 2;
        else
                daemon $DAEMON $DAEMON_ARGS
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch /var/lock/subsys/crtmpserver
                return $RETVAL
        fi

}

stop() {
        echo -n "Shutting down crtmpserver Server: "
        #echo
        killproc crtmpserver
        echo
        rm -f /var/lock/subsys/crtmpserver
        return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status crtmpserver
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
